### ISSUE TITLE
Missing Description, Tags in IAMRoleProperties

### ISSUE THREAD

**Issue by jebefor** [Skyscanner/pycfmodel#107]
Hi!

It looks like the properties "Description" and "Tags" are missing from `IAMRoleProperties` (if compared to [AWS IAM Role definition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html)) and that's provoking that valid IAM Roles are instantiated with `GenericResource`.

Is there a reason why these two properties are not part of the `IAMRoleProperties` class? 
I would be glad to send a PR if it needs fixing.

**Comment by w0rmr1d3r** [comment]
Hi @jebefor , I'll take this issue with the team internally and come back with an answer/fix.
Thank you for raising it 🤗

**Comment by w0rmr1d3r** [comment]
HI @jebefor 
The issue has been closed since the PR has been merged.
The fix is available for version `0.20.2`.
Thank you for spotting it 🚀

**Comment by jebefor** [comment]
Really appreciate your quick support. Thank you!! 👏
